/// Flutter icons Call_star
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Call_star
///      fonts:
///       - asset: fonts/Call_star.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Call_star {
  Call_star._();

  static const _kFontFam = 'Call_star';

  static const IconData call_star = const IconData(0xe800, fontFamily: _kFontFam);
}
