/// Flutter icons Entro1
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
// /   fonts:
// /    - family:  Entro1
// /      fonts:
// /       - asset: fonts/Entro1.ttf
// /
///
///
import 'package:flutter/widgets.dart';

class Entro1 {
  Entro1._();

  static const _kFontFam = 'Entro1';

  static const IconData entro1 = const IconData(0xe801, fontFamily: _kFontFam);
}
