/// Flutter icons Forgetpassword
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Forgetpassword
///      fonts:
///       - asset: fonts/Forgetpassword.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Forgetpassword {
  Forgetpassword._();

  static const _kFontFam = 'Forgetpassword';

  static const IconData forgetpassword = const IconData(0xe805, fontFamily: _kFontFam);
}
