/// Flutter icons Home_bacground
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Home_bacground
///      fonts:
///       - asset: fonts/Home_bacground.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Home_bacground {
  Home_bacground._();

  static const _kFontFam = 'Home_bacground';

  static const IconData home_bacground = const IconData(0xe806, fontFamily: _kFontFam);
}
